package com.mygaienko.common.algorithms.leetcode.rank_teams_by_votes;

import org.junit.Test;

import static org.assertj.core.api.AssertionsForInterfaceTypes.assertThat;

public class SolutionTest {

    Solution solution = new Solution();

    @Test
    public void test() {
        var actual = solution.rankTeams(new String[]{"ABC", "ACB", "ABC", "ACB", "ACB"});
        assertThat(actual).isEqualTo("ACB");
    }

    @Test
    public void test3() {
        var actual = solution.rankTeams(new String[]{"BCA", "CAB", "CBA", "ABC", "ACB", "BAC"});
        assertThat(actual).isEqualTo("ACB");
    }

    @Test
    public void test24() {
        var actual = solution.rankTeams(new String[]{
                "PGAOFXIKYJVSLTUHCZQRE", "LSIAPTHYCGURKEZXJOFQV", "UGSARZICOXYPHTQFJKVEL", "XIAOKSVGRJCHQZUETLYPF", "OHRXPGEVUYCSKZILQATFJ",
                "UHFSCZVKIELGOQJYRXPAT", "QECXVZKJTLIYHUFRGOSAP", "RJGAZIKPEVUSTOXFQYCHL", "XRFGPAQSJOETHVCZIKLUY", "ZCTQOVRFKXJGEALSHIYUP",
                "QGTEHXCJRIPSUZALOYFVK", "GIHXVJPQYOSZFRKLEUTAC", "LURXHFECKZSYPTQGAOJVI", "TFUKZELVARQCXIYPJHGSO", "FIPYTACSXZKLRGOHJVEQU",
                "ZKJQOGHVURAISXFLPYECT", "XKOJAHVQUCETFPRYZGLSI", "TUKZAVIFXEGQCSOLJRPHY", "OSIPCFVRLAYKEHZTJGUQX", "OYAQTCEKLGPRZVISUXFHJ",
                "SKHCXEZLTFVQOIUPRAJGY", "CRZPAEILFTOKUJVGXHQYS", "OQVLPEYZFIGJRKUSXAHTC", "VQTXURZKAPGHEIFCOLSJY", "YVRZKXSOAEIPUQJHGCFLT",
                "YEJTGFQPOZLCARSUIKVHX", "XKASIECRHVQFPULZTOGJY", "KAQVYSZLTFXCGEJIRUHOP", "IYJXCUTOAPQKHEZFGRVSL", "OIEPRLZGUVQHSYJAFTXCK",
                "CIGVAZLKORXQYPHTEUSFJ", "UVTCJFQOGXIZHLKYRASEP", "FCVOYSJHZLKATXRIUPQGE", "TJLQFSRKIUGPCVZHOEAXY", "FUHLSRGTCOXAEZVQIYKPJ",
                "CAGRHEUQZISYKXLFVPJOT", "LASKUHEPJQXRCTZOVIYFG", "IGKJSYLVFCUXETRAHZQPO", "UZGXPIAFVOSLKRYQJTCHE", "VKELXAFPOGSRIZCUQYTHJ",
                "GCTJEUFRVLKAIOYSHZXQP", "PHUOAXLYFTCRSEQIKGJZV", "XLQYSIJHTREFPOKCUGVAZ", "LUZXHQKIATOCGJYPFSVRE", "XILVQZAFUKECYJGTPHSOR",
                "GCQFHJKTAERVPIYUSZOLX", "ZPRILGHYXTFVSQCAUKEOJ", "SLFTYQPZKUAIVGRHEOCXJ", "FCUVEOKHGZQSYJRXPAILT", "AKZJRQCPVHYGSXLFITUOE",
                "OKVEHCXPYRUGIAZJQFSLT", "YZVHPIGSLREJQCXOKFATU", "QTCILUZFVYHSAPGJEKXRO", "YXKJOPHIVGARUTZEFLSCQ", "OZPXURLHEKFQTSIVJYGCA",
                "YIVEGRJLTPOAZFCQSUXHK", "VPQUXLYGACSITFKEJHORZ", "AOEQLYPFZUXCKHSTVIJRG", "IFYTULEXKZRCOHASQPJGV", "TASULVYKZPOCGIHJERXFQ",
                "RGXYZCHVEAPTJISQUFKOL", "XKVRTHJSLOZPIAYUEQGFC", "EYIRXQTCUPHSVJFZLAKOG", "ZRJSTQIGPELKUCHAOYVFX", "EIXJPTZGRKVYCUFAOHQLS",
                "LRSGUJZYXCIVQOAHTFPEK", "ZHLOESVGIARXCUQYKPFJT", "ZKQLVGOIFASTPUHYJRCXE", "ZLPJQYTXEGAFHOSRCIUVK", "ZVHYQJXCGTAFKLEISOPUR",
                "KZGLYEQAURFHSXIVPTJCO", "TIXPAYEKJLVGCQRUHOSZF", "ESORYCVXLPKZFQJAUGIHT", "FAJTCHORZGLIKXYSVUPQE", "AOXHJEZFYLIQCPRVTSGKU",
                "IZVAPOTEHCJQLKRGFUSXY", "RTVYZHSIPGCEKJQUAXFOL", "GSHOKEXAZCIQYTRJFVLPU", "SXZLKIUGEVCPFHTQJARYO", "QPCOTHISGLKYJFUAZXVRE",
                "XPUEYATJHCOLVGSQRIZKF", "GIKSZFHEQLTCVXJAYOPUR", "RFSOEJPUAGKYHZIQCTLXV", "UFHXJLITQPEGCKOSZYRAV", "ZVQAFGXEIRSTPJYLHCOKU",
                "ZITVJLSOAUGPCFYXHRQKE", "RCZOIPEXFJAQGSYVLKHUT", "TUHVJROCXIGEPLQAZYKSF", "ATQJGKUIPLZXEYCRSOVFH", "TVHYLSRAKIXJFGEPOZUCQ",
                "CAPHZLGXQSIRTJYFOKEVU", "FAYOKHEUZIRJXQTVGCSPL", "IJCRUHVAPFYKGXLTSOQEZ", "ZKIJLQEAUVHFTYRXCSGOP", "ALFTJSRXUQPIOVZCYHEKG",
                "ZASIVJQYUCRPEKGLTXFHO", "OICQXZPEFUSTVALKGYRJH", "ZOKVPHUXGRQIJCSEYALFT", "FKACPHOSIREGUTYLJXZVQ", "IZXOREFGSLPKUHAYCVTJQ",
                "UVXZTCFAQEYLORSKHPJIG", "PKVQCYSTLHRZIFAUEXJGO", "IRFZSKGEHQVOLXCTJUPAY", "XYHPVOTILEAUZJGSKQCRF", "ERXJLFZQIGHPCSTYKUVOA",
                "SZTIFCGVEKUJYPAOQXHRL", "JPTGQOEYFIKURCVHXALZS", "URJGTXZKICAOQSLVEYHFP", "ZERGKOLTSUIXJFACVQHPY", "GQCVAJYIKRZLTPSFHOUEX",
                "OKRCTSGLZXQJEHPFVYUIA", "GUKXARTQFYSCVEZIOJHLP", "UTCIRLFHGJOSYZVPQKEAX", "JPIOVSFZHUTQKCERXAGLY", "LKJEGOHRTYQFXUSCVIPZA",
                "LSETPUAHZYOICVRGJFXKQ", "OPGHRVUXQEYLZFISTJKCA", "VOKCSGFTXZEIRYALHJPQU", "POTXFYCQIVZHLGJERAUSK", "FAUIECXOYPLRHJKTSZQVG",
                "XFAETYRCJUGVPQZOKSLHI", "LGCVYIAZRFJSHQXTKUOPE", "YKATQFIURCHPLSVGJEXOZ", "IRUHTAXVYZKFPSEOJCLGQ", "TAVEXIHLPOGSZRCJFQKUY",
                "GFACLJSETKIXRZUYHVPOQ", "XTJKSAZIQYRCLPGOHUFEV", "GSFTZLJCVKRYUOXAQIEPH", "GIOLPRXHCSUFKAVTJZEQY", "SFCRPVGYKOUZJALQEXHIT",
                "EUTOKQGFCLRAVZPJYSXHI", "UOYSHGLTPZXRICFJEKAVQ", "OTZIGVXSQHCPRYUKELAJF", "SGZOEHLKYUPXCJRFTAVQI", "JOCVZLGSUIAHPFKYTQERX",
                "ZFSRJULQGKIOXEPYHTACV", "FGSJCIYXHEAZTOLUKRVQP", "YXHICZVFTSQJKLPOURGAE", "XALRUOHJZYVEGQPKCSFIT", "KCIJLRXYHAESGFQUOPVZT",
                "AUTSXLECOGPZIHRVYQKFJ", "GIZRAKEVOXLTCJSUHQPFY", "ZKUPCORTFYEIAGJQXVLHS", "JALHXZQIYSUROPCEGKVFT", "KUIGTSQAJEOZYPCFHLXRV",
                "LXICRFZJEUVYASPKQHTOG", "EFUPZKRXLCAVJGQITHOSY", "EUYGQKARZJVHLIPFCOSTX", "AOXTKHRYLJZQEUCSPGVIF", "SHUTLZEGRJYPCVAFXQOKI",
                "GUZTAXQLKIRFYEOHJSPVC", "RGOZPAXLYVJSHFICKTQUE", "ASCHFQVTRLEKYUZIXGJPO", "CQFRUSIXLOZPVJTGYAHEK", "VGYURSHEXIKCFOAPTQLJZ",
                "VFQCGPEAYISTXKORLUJHZ", "UZJOYGVRETFSPLQAIKHCX", "JKQRZFXICESTHPGOUYVAL", "XGFYRJKCVTESZPHLQUIOA", "YEPGFRALQOKJTXSZCIUVH",
                "CXHPFAYKVZQORLJUTEGSI", "PXHACSGJUILTYVQRFKEOZ", "RSILHFAYCQJKVUGZTPXOE", "IKAEOXFVPHSLRCQGZYJTU", "GVKRJFLXZUOSAEIYPTCQH",
                "TEXZOUVPICHGFLRYSQKAJ", "JCEHLTRZQVFOPUSIKGYXA", "GFLJHYXEAQTOPSKIUZVRC", "ZGKJFVEAUHIXRTCLSPYQO", "GXOTELHIQKUAFSVRPZYCJ",
                "XRZEUGOIVAKSYPHJQCFLT", "PYQVXGHSAKLRFTEZOUICJ", "QGHOCVKFEPUTSRAIJYZLX", "YRQVOLKJGFIXHEPCTUAZS", "CTXYFQVZASEHPIOUJGRLK",
                "GIZHRVQLJEYAKTSUCOPXF", "XIGKSCLTRYJHZFUOQAPVE", "RYCXPSEGIFAULKZTQJVHO", "PXEQTGYSHICLAVRUZKJOF", "AERXGTIHLUZSFKQYVPCJO",
                "SKTPVFXILUZHYCEJAQROG", "OCQUZKSJYLIVARFEHTPGX", "ISZXFQUKHJOTCREPGYALV", "LOSTQCIRZFVGYKPEAJHUX", "QPFTRGUKOIVXESYCJZLAH",
                "PXSUEIVOHZCKJFQLTGRAY", "QYLRCVJOPEXGUTZKSAIFH", "RJQPOFKXIHUZYVETCSLAG", "HTFJEAISYQZUXLCGVPORK", "ECGFLAHQJPORITXYUKVZS",
                "FJGAIOSPTVXUZYHLQKERC", "GEQLKYPICTUAFRSOVXZHJ", "CGJHEZKSTIUQOFVRYXLAP", "XYJSGTIKOVUFERLHCPAQZ", "LQFVECITUGXHOYJKASRZP",
                "HYGJQFUPZVORSKICLETXA", "ACTXZRUYPOJLIEFSKQVGH", "PHOLYCFUKRASEGTVQZXIJ", "RTUOEZHPSKAFXLQYICVGJ", "RAPTGQIJOSEFZUKVXCLHY",
                "EUAKTQLJFOHCPSYVGRZXI", "TYUPHSXVEZKIFQACRLJGO", "ZHOEAIULSVJQKGRYFTXPC", "CPEUIGVRFSOZAKYHQLTJX", "ZCOEYRHVQFLSJIXUATGKP",
                "FGSCJZKUTRVOLEYHQIPAX", "SPKIGAUVQJXZYEHROCFTL", "ITQVPZLEOGJUHKXRYFASC", "GSAFTOHJQCYLUVPZEXRKI", "ZPFKXLUJSRCAHOGYTVIEQ",
                "QIFYPTAJELCSOXUKRZGVH", "JFGZCQAELXKOIUHYRSTVP", "TIGPACUOYZJHXKSVQEFRL", "EATKLFGOCZVQHXRYSJIPU", "SPOJYHVQXGZELUACKFITR",
                "YTVIQXEZUJRFGCOLKSAPH", "SPGHEQZJVXKIOAYLRUCFT", "RFXCSUZIJAQTELHKVPOGY", "PHXJESZRGFLKOAVIQUTYC", "GUYCOKILATEJZXHFPRSVQ",
                "GQTUFLAKCPVRYIOHXEZJS", "AYVCGFTIQKLZSXEPHRJUO", "EAXRUTPZVHCGLISYQFKOJ", "SUVFHQGRLXEZAYJTCIPKO", "PXKTOGRLHQAJFZCIYUSVE",
                "ZGXYPLOSRCTAVFEUIQKHJ", "OKEHXFQSIZGCRJLPATYUV", "YXQILGVKPJOUTAZRCSEHF", "TYQAGXSCZVKLJEOIHPURF", "ELAJZPXRIFQVSGKTOCUHY",
                "YIPXUJHGACTVQEKSOZRLF", "ZPAGUYLVSRCIKOJXFTEQH", "LYKIJURAEGVZSFPXHCOTQ", "EULYFIOJTGXZQCPARHKSV"});
        assertThat(actual).isEqualTo("ZGXOEYTSRLIAPFUCQJVKH");
    }
}